import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen items-center justify-center bg-gray-900">
          <main className="flex flex-col bg-[url(/bg.svg)] bg-cover bg-no-repeat md:w-100.5 h-dvh px-6 overflow-x-hidden overflow-y-scroll">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
