import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative w-full min-h-screen overflow-hidden">
          <img
            src="/bg.svg"
            alt=""
            className="
      pointer-events-none
      select-none
      fixed
      inset-0
      w-full
      h-full
      object-cover
      -z-10
    "
          />

          <main className="relative z-10 px-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
